### ISSUE TITLE
Federation with Pleroma

### ISSUE THREAD

**Issue by skysarwer** [michaelcpuckett/ap-groups#1]
Groups on Chirp Social do not seem to be discoverable on Pleroma instance.

I've tested by trying to find @art@chirp.social on a number of Pleroma servers (public.garden & stereophonic.space) with no results.

**Comment by michaelcpuckett** [comment]
Thanks for pointing this out! I hadn't used Pleroma before but I signed up for an account and can confirm it doesn't show up.

Mastodon is also a little flaky. I think maybe due to some kind of caching there...

I added `.well-known/host-meta` after taking a look at their documentation. This might have helped, but still appearing in results.

Here's my server log after I looked it up from Pleroma:

```
INCOMING: / .well-known /host-meta
INCOMING: / .well-known/webfinger?resource=acct:art@chirp.social
INCOMING: /@art
```

It does seem like it's following the trail from host-meta -> webfinger -> account profile. So I'm surprised it doesn't appear.

I'll keep looking into it, thanks again!

**Comment by skysarwer** [comment]
Great! Thanks for looking into it, and for the great app. 

Yea, I also noticed it being flaky on Mastodon. When I follow a group, it stays stuck as "Follow request sent".

**Comment by michaelcpuckett** [comment]
I added well-known/nodeinfo without any luck as well.

I wasn't able to look up any Mastodon profile on any Pleroma instance using the @user@domain syntax or even with a direct URL. So I'm starting to wonder if profile discovery is possible?

@skysarwer What's your experience with searching for Mastodon profiles on Pleroma?

**Comment by michaelcpuckett** [comment]
I also see that @wordpress has 0 followers, so there must have been some kind of issue with follow/accept handshake. If you have time, please try to unfollow and re-follow.

**Comment by skysarwer** [comment]
@michaelcpuckett Profile discovery on Pleroma has been working fine for me. What handles where you searching, if I may ask? If you were testing on the Public Garden server, I did notice that it was a little slow today so that may have affected things.

**Comment by skysarwer** [comment]
> I also see that @WordPress has 0 followers, so there must have been some kind of issue with follow/accept handshake. If you have time, please try to unfollow and re-follow.

Confirmed that following is now working on Mastodon! That's awesome :)

**Comment by michaelcpuckett** [comment]
@skysarwer Thank you so much for trying again! That helped me debug.

The handshake isn't working because when attempting to GET the profile, it's hitting response 401 "Request not signed"

I can verify by using Postman/CURL to GET https://c.im/users/evn with Accept header set to `application/activity+json`

I haven't seen this with other Mastodon accounts so far but I think it's due to an optional Secure Mode that Mastodon servers can turn on.

https://docs.joinmastodon.org/spec/security/

> When secure mode is enabled, all GET requests require HTTP signatures as well.

I will look into how to implement that ASAP.

**Comment by michaelcpuckett** [comment]
Regarding Pleroma, I'm having trouble telling if this recent PR handles remote domain webfinger discovery and maybe some servers don't have it yet?

https://git.pleroma.social/pleroma/pleroma/-/merge_requests/3361#note_96475

**Comment by michaelcpuckett** [comment]
OK I have updated the upstream code to send HTTP signatures.

**Comment by michaelcpuckett** [comment]
Looks like now instead of "Request not signed", Mastodon in Secure Mode is sending "Verification failed" so I must have implemented it incorrectly. I'll take another look.

**Comment by michaelcpuckett** [comment]
I updated the HTTP signature code again to properly format GET requests.

You can try again @skysarwer - wish I had a better way to test, sorry about that!

**Comment by michaelcpuckett** [comment]
I realized I could sign up for a c.im account, so assuming that the entire server is in Secure Mode, I was able to make the follow/accept handshake from that server. I think that issue is closed.

**Comment by michaelcpuckett** [comment]
Re: Pleroma profile discovery

When I go to https://blob.cat/main/public -> Search box, and search for:

FAILS: @art@chirp.social
FAILS: https://chirp.social/@art
FAILS: @mxp@c.im
FAILS: https://c.im/users/mxp
FAILS: @mastodon@mastodon.social

Although the docs say remote profile discovery is supported:

https://docs-develop.pleroma.social/backend/configuration/how_to_serve_another_domain_for_webfinger/

It seems based on this comment that it's not supported yet or has just been released:

https://git.pleroma.social/pleroma/pleroma/-/merge_requests/3361#note_96475

If you are able to look up Mastodon profiles from your Pleroma instance, please let me know. If not, I think this can be closed.

**Comment by skysarwer** [comment]
> I realized I could sign up for a c.im account, so assuming that the entire server is in Secure Mode, I was able to make the follow/accept handshake from that server. I think that issue is closed.

That is working on my end too! Looks like it is closed indeed. Thank you so much, that is incredible.

**Comment by skysarwer** [comment]
Just sharing some screenshots of https://c.im/@mxp and some gup.pe groups being on Public Garden (via Pleroma)

![Screenshot 2022-11-30 220859](https://user-images.githubusercontent.com/81714339/204957022-8257f93a-74be-455a-8309-7bc2a6f15046.jpg)
![Screenshot 2022-11-30 220958](https://user-images.githubusercontent.com/81714339/204957025-d516e91a-798f-4a9b-bd3e-cffaba70d662.jpg)

**Comment by michaelcpuckett** [comment]
Thanks for providing that info! I was able to log in and see my own account on Mastodon but not any chirp.social accounts, so the issue is verified.

In the server logs I see requests to host-meta, webfinger, and the account profile being search for.

I looked at my host-meta again and where it needed to return XML it was invalid because there was whitespace at the start.

I tested again since making that change but it still doesn't fix the issue.

I'm wondering what's different about Pleroma (vs Mastodon and Friendica) -- I'll do some more digging soon.

**Comment by michaelcpuckett** [comment]
I tried a couple things:

* Returning the appropriate JSON-LD `@context` for actors (W3ID in addition to ActivityStreams)
* Returning XML for webfinger (https://git.pleroma.social/pleroma/pleroma/-/issues/2989)

Neither seemed to work so far.

Going to continue looking through the Pleroma issues for discovery-related topics.

**Comment by michaelcpuckett** [comment]
OK, I have isolated the issue.

Pleroma does not support when an actor's profile's `type` is an array.

I opened an issue on their tracker:

https://git.pleroma.social/pleroma/pleroma/-/issues/3013

I have been generating actors with `type: [ 'Group' ]` but I will update that to be just `type: Group`.

**Comment by michaelcpuckett** [comment]
OK fixed for me! Please let me know if you still see any issues.

**Comment by skysarwer** [comment]
Confirmed it's working on my end too! Amazing work! Super exciting.
